name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: List files
      run: |
        ls -R
    - name: Install Dependencies
      working-directory: ./backend-skf
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Build Docker image
      run: |
        docker build -t ahma25/skf-management:latest .
    - name: Push Docker image
      run: |
        docker push ahma25/skf-management:latest
    - name: Deploy to Render
      run: | 
        render services redeploy ${{ secrets.RENDER_SERVICE_ID }} \
        --api-key ${{ secrets.RENDER_API_KEY }}